package clientui;

import client.ParkingClient;
import java.awt.Color;
import serviceui.Printer;


public class AutoParkGUI extends javax.swing.JFrame implements Printer {

    private ParkingClient client;

    public AutoParkGUI() {
        initComponents();
    }

    public AutoParkGUI(ParkingClient aThis) {
        this();
        this.client = aThis;
        EngineOn.setEnabled(true);
        EngineOff.setEnabled(false);
        ParkingSensor.setEnabled(false);
        StopCar.setEnabled(false);
        AutoPark.setEnabled(false);
        DriveCar.setEnabled(false);
        IncreaseSpeed.setEnabled(false);
        DecreaseSpeed.setEnabled(false);
        Information.setEnabled(false);

    }
    
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EngineOn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        EngineOff = new javax.swing.JButton();
        ParkingSensor = new javax.swing.JButton();
        StopCar = new javax.swing.JButton();
        AutoPark = new javax.swing.JButton();
        DriveCar = new javax.swing.JButton();
        IncreaseSpeed = new javax.swing.JButton();
        DecreaseSpeed = new javax.swing.JButton();
        Information = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        EngineOn.setText("Engine on");
        EngineOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineOnActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        EngineOff.setText("Engine Off");
        EngineOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EngineOffActionPerformed(evt);
            }
        });

        ParkingSensor.setText("Parking Sensor");
        ParkingSensor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ParkingSensorActionPerformed(evt);
            }
        });

        StopCar.setText("Stop");
        StopCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StopCarActionPerformed(evt);
            }
        });

        AutoPark.setText("Auto Park");
        AutoPark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutoParkActionPerformed(evt);
            }
        });

        DriveCar.setText("Drive");
        DriveCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriveCarActionPerformed(evt);
            }
        });

        IncreaseSpeed.setText("Increase Speed");
        IncreaseSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncreaseSpeedActionPerformed(evt);
            }
        });

        DecreaseSpeed.setText("Decrease Speed");
        DecreaseSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecreaseSpeedActionPerformed(evt);
            }
        });

        Information.setText("Info");
        Information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EngineOn)
                            .addComponent(AutoPark))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EngineOff)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ParkingSensor))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(DriveCar)
                                .addGap(34, 34, 34)
                                .addComponent(StopCar)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(23, 23, 23))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(IncreaseSpeed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DecreaseSpeed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Information)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EngineOn)
                            .addComponent(EngineOff)
                            .addComponent(ParkingSensor))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(StopCar)
                            .addComponent(AutoPark)
                            .addComponent(DriveCar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IncreaseSpeed)
                            .addComponent(DecreaseSpeed)
                            .addComponent(Information))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EngineOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineOnActionPerformed
             
        
        client.turnengineon();
        EngineOn.setEnabled(false);
        EngineOff.setEnabled(true);
        ParkingSensor.setEnabled(true);
        AutoPark.setEnabled(false);
        DriveCar.setEnabled(true);
        StopCar.setEnabled(false);
        IncreaseSpeed.setEnabled(false);
        DecreaseSpeed.setEnabled(false);
        Information.setEnabled(true);


   


    }//GEN-LAST:event_EngineOnActionPerformed

    private void EngineOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EngineOffActionPerformed
        client.turnengineoff();
        ParkingSensor.setEnabled(false);
         EngineOn.setEnabled(true);
        EngineOff.setEnabled(false);
        AutoPark.setEnabled(false);
        DriveCar.setEnabled(false);
        StopCar.setEnabled(false);
        IncreaseSpeed.setEnabled(false);
        DecreaseSpeed.setEnabled(false);
       Information.setEnabled(false);



      
    }//GEN-LAST:event_EngineOffActionPerformed

    private void ParkingSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ParkingSensorActionPerformed
        client.sensor();
        AutoPark.setEnabled(false);
        ParkingSensor.setEnabled(true);
        AutoPark.setEnabled(true);
        DriveCar.setEnabled(true);
        
        
    
        
    }//GEN-LAST:event_ParkingSensorActionPerformed

    private void StopCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StopCarActionPerformed
        client.stop();
        DriveCar.setEnabled(true);
        IncreaseSpeed.setEnabled(false);
        DecreaseSpeed.setEnabled(false);
        

        

        
        // TODO add your handling code here:
    }//GEN-LAST:event_StopCarActionPerformed

    private void AutoParkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutoParkActionPerformed
        client.autopark();
        AutoPark.setEnabled(false);
        DriveCar.setEnabled(true);
        ParkingSensor.setEnabled(false);


        

        
// TODO add your handling code here:
    }//GEN-LAST:event_AutoParkActionPerformed

    private void DriveCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriveCarActionPerformed
   client.drive();
    DriveCar.setEnabled(false);
    IncreaseSpeed.setEnabled(true);
    DecreaseSpeed.setEnabled(true);
    ParkingSensor.setEnabled(true);
    StopCar.setEnabled(true);




        
        // TODO add your handling code here:
    }//GEN-LAST:event_DriveCarActionPerformed

    private void IncreaseSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncreaseSpeedActionPerformed
client.increasespeed();
        // TODO add your handling code here:
    }//GEN-LAST:event_IncreaseSpeedActionPerformed

    private void DecreaseSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecreaseSpeedActionPerformed
client.decreasespeed();
        // TODO add your handling code here:
    }//GEN-LAST:event_DecreaseSpeedActionPerformed

    private void InformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformationActionPerformed
 client.showdetails();
        // TODO add your handling code here:
    }//GEN-LAST:event_InformationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParkingClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParkingClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParkingClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParkingClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoParkGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AutoPark;
    private javax.swing.JButton DecreaseSpeed;
    private javax.swing.JButton DriveCar;
    private javax.swing.JButton EngineOff;
    private javax.swing.JButton EngineOn;
    private javax.swing.JButton IncreaseSpeed;
    private javax.swing.JButton Information;
    private javax.swing.JButton ParkingSensor;
    private javax.swing.JButton StopCar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public void append(String string) {
        jTextArea1.append("\n" + string);
    }

    public void clear() {
        jTextArea1.setText("");
    }
}
