package clientui;

import client.FridgeClient;
import serviceui.Printer;

/**
 *
 * @author dominic
 */
public class FridgeClientGUI extends javax.swing.JFrame implements Printer {

    private FridgeClient client;

    public FridgeClientGUI() {
        initComponents();
    }

    public FridgeClientGUI(FridgeClient aThis) {
        this();
        this.client = aThis;
        TurnFridgeOff.setEnabled(false);
        LockIce.setEnabled(false);
        UnlockIce.setEnabled(false);
        DecreaseTemp.setEnabled(false);
        IncreaseTemp.setEnabled(false);
        DispenseIce.setEnabled(false);

        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        turnFridgeOn = new javax.swing.JButton();
        TurnFridgeOff = new javax.swing.JButton();
        DispenseIce = new javax.swing.JButton();
        LockIce = new javax.swing.JButton();
        UnlockIce = new javax.swing.JButton();
        IncreaseTemp = new javax.swing.JButton();
        DecreaseTemp = new javax.swing.JButton();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        turnFridgeOn.setText("Turn Fridge On");
        turnFridgeOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turnFridgeOnActionPerformed(evt);
            }
        });

        TurnFridgeOff.setText("Turn Fridge OFF");
        TurnFridgeOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TurnFridgeOffActionPerformed(evt);
            }
        });

        DispenseIce.setText("Dispense Ice");
        DispenseIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispenseIceActionPerformed(evt);
            }
        });

        LockIce.setText("Lock Ice");
        LockIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LockIceActionPerformed(evt);
            }
        });

        UnlockIce.setText("Unlock Ice");
        UnlockIce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnlockIceActionPerformed(evt);
            }
        });

        IncreaseTemp.setText("Increase Temp");
        IncreaseTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncreaseTempActionPerformed(evt);
            }
        });

        DecreaseTemp.setText("Decrease Temp");
        DecreaseTemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecreaseTempActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(turnFridgeOn)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(UnlockIce)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(DispenseIce)
                                        .addGap(41, 41, 41))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(116, 116, 116)
                                        .addComponent(TurnFridgeOff)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LockIce)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DecreaseTemp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IncreaseTemp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 155, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(turnFridgeOn)
                    .addComponent(TurnFridgeOff))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LockIce)
                    .addComponent(DecreaseTemp)
                    .addComponent(IncreaseTemp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UnlockIce)
                    .addComponent(DispenseIce))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void turnFridgeOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turnFridgeOnActionPerformed
  client.turnthefridgeon();
  TurnFridgeOff.setEnabled(true);
  LockIce.setEnabled(true);
  IncreaseTemp.setEnabled(true);
  DispenseIce.setEnabled(true);
  UnlockIce.setEnabled(false);



    }//GEN-LAST:event_turnFridgeOnActionPerformed

    private void TurnFridgeOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TurnFridgeOffActionPerformed
    client.turnthefridgeoff();
  turnFridgeOn.setEnabled(true);
  LockIce.setEnabled(false);
  IncreaseTemp.setEnabled(false);
  DispenseIce.setEnabled(false);
  UnlockIce.setEnabled(false);

    }//GEN-LAST:event_TurnFridgeOffActionPerformed

    private void LockIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LockIceActionPerformed
    client.lockthefridge();
    UnlockIce.setEnabled(true);

    
    }//GEN-LAST:event_LockIceActionPerformed

    private void UnlockIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnlockIceActionPerformed
    client.unlockthefridge();
    LockIce.setEnabled(false);

        // TODO add your handling code here:
    }//GEN-LAST:event_UnlockIceActionPerformed

    private void DecreaseTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecreaseTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DecreaseTempActionPerformed

    private void IncreaseTempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncreaseTempActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IncreaseTempActionPerformed

    private void DispenseIceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispenseIceActionPerformed
    client.dispenseIce();

    }//GEN-LAST:event_DispenseIceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FridgeClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FridgeClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FridgeClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FridgeClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FridgeClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DecreaseTemp;
    private javax.swing.JButton DispenseIce;
    private javax.swing.JButton IncreaseTemp;
    private javax.swing.JButton LockIce;
    private javax.swing.JButton TurnFridgeOff;
    private javax.swing.JButton UnlockIce;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton turnFridgeOn;
    // End of variables declaration//GEN-END:variables

    public void append(String string) {
        jTextArea1.append("\n" + string);
    }

    public void clear() {
        jTextArea1.setText("");
    }
}
