package clientui;

import client.PhoneClient;
import java.awt.Color;
import serviceui.Printer;

/**
 *
 * @author dominic
 */
public class PhoneClientGUI extends javax.swing.JFrame implements Printer {

    private PhoneClient client;

    public PhoneClientGUI() {
        initComponents();
    }

    public PhoneClientGUI(PhoneClient aThis) {
        this();
        this.client = aThis;
        PhoneOn.setEnabled(true);
        PhoneOn.setForeground(Color.RED);
        PhoneOff.setEnabled(false);
        PhoneOff.setForeground(Color.RED);
        PlaySong.setEnabled(false);
        PlaySong.setForeground(Color.RED);
        ConnectSpeaker.setEnabled(false);
        ConnectSpeaker.setForeground(Color.ORANGE);
        RadioOn.setEnabled(true);
        RadioOn.setForeground(Color.ORANGE);
        RadioOff.setEnabled(false);
        RadioOff.setForeground(Color.ORANGE);
        IncreaseVolume.setEnabled(false);
        IncreaseVolume.setForeground(Color.ORANGE);
        DecreaseVolume.setEnabled(false);
        DecreaseVolume.setForeground(Color.ORANGE);


    }
    
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PhoneOn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        PhoneOff = new javax.swing.JButton();
        ConnectSpeaker = new javax.swing.JButton();
        IncreaseVolume = new javax.swing.JButton();
        DecreaseVolume = new javax.swing.JButton();
        PlaySong = new javax.swing.JButton();
        RadioOn = new javax.swing.JButton();
        RadioOff = new javax.swing.JButton();
        RandomStation = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PhoneOn.setText("Phone On");
        PhoneOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneOnActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        PhoneOff.setText("Phone Off");
        PhoneOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneOffActionPerformed(evt);
            }
        });

        ConnectSpeaker.setText("Connect Radio");
        ConnectSpeaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConnectSpeakerActionPerformed(evt);
            }
        });

        IncreaseVolume.setText("Volume Up");
        IncreaseVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncreaseVolumeActionPerformed(evt);
            }
        });

        DecreaseVolume.setText("Volume Down");
        DecreaseVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecreaseVolumeActionPerformed(evt);
            }
        });

        PlaySong.setText("Play Song");
        PlaySong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaySongActionPerformed(evt);
            }
        });

        RadioOn.setText("Radio On");
        RadioOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioOnActionPerformed(evt);
            }
        });

        RadioOff.setText("Radio Off");
        RadioOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioOffActionPerformed(evt);
            }
        });

        RandomStation.setText("Random Station");
        RandomStation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomStationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PhoneOn)
                        .addGap(18, 18, 18)
                        .addComponent(ConnectSpeaker)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IncreaseVolume))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(PhoneOff)
                            .addGap(18, 18, 18)
                            .addComponent(RadioOn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DecreaseVolume))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(PlaySong)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(RadioOff)
                            .addGap(18, 18, 18)
                            .addComponent(RandomStation))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneOn)
                            .addComponent(ConnectSpeaker)
                            .addComponent(IncreaseVolume))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneOff)
                            .addComponent(DecreaseVolume)
                            .addComponent(RadioOn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RadioOff)
                            .addComponent(PlaySong)
                            .addComponent(RandomStation))
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PhoneOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneOnActionPerformed
        client.turnphoneon();
        PhoneOff.setEnabled(true);
        ConnectSpeaker.setEnabled(false);
        RadioOff.setEnabled(false);
        IncreaseVolume.setEnabled(true);
        DecreaseVolume.setEnabled(true);
        PlaySong.setEnabled(true);
   


    }//GEN-LAST:event_PhoneOnActionPerformed

    private void PhoneOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneOffActionPerformed
        client.turnphoneoff();
        PhoneOff.setEnabled(false);
        ConnectSpeaker.setEnabled(false);
        RadioOn.setEnabled(true);
        RadioOff.setEnabled(false);
        IncreaseVolume.setEnabled(true);
        DecreaseVolume.setEnabled(false);
        PlaySong.setEnabled(false);
      
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneOffActionPerformed

    private void ConnectSpeakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConnectSpeakerActionPerformed
        client.connectdevice();
        PhoneOff.setEnabled(true);
        ConnectSpeaker.setEnabled(true);
        RadioOn.setEnabled(false);
        RadioOff.setEnabled(false);
        IncreaseVolume.setEnabled(true);
        DecreaseVolume.setEnabled(false);
        PlaySong.setEnabled(false);
    

    
        // TODO add your handling code here:
    }//GEN-LAST:event_ConnectSpeakerActionPerformed

    private void RadioOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioOnActionPerformed
        client.turnradioon();
        ConnectSpeaker.setEnabled(true);
        RadioOn.setEnabled(false);
        RadioOff.setEnabled(true);
        IncreaseVolume.setEnabled(true);
        DecreaseVolume.setEnabled(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_RadioOnActionPerformed

    private void RadioOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioOffActionPerformed
        client.turntheradiooff();
        client.turnradioon();
        PhoneOff.setEnabled(true);
        ConnectSpeaker.setEnabled(false);
        RadioOn.setEnabled(true);
        RadioOff.setEnabled(false);
        IncreaseVolume.setEnabled(true);
        DecreaseVolume.setEnabled(false);
        PlaySong.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioOffActionPerformed

    private void IncreaseVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncreaseVolumeActionPerformed
        client.volumeUp();
        PhoneOff.setEnabled(false);
        ConnectSpeaker.setEnabled(false);
        RadioOn.setEnabled(true);
        RadioOff.setEnabled(false);
        IncreaseVolume.setEnabled(true);
        DecreaseVolume.setEnabled(false);
        PlaySong.setEnabled(false);
    }//GEN-LAST:event_IncreaseVolumeActionPerformed

    private void PlaySongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaySongActionPerformed

       PhoneOff.setEnabled(false);
        ConnectSpeaker.setEnabled(false);
        RadioOn.setEnabled(true);
        RadioOff.setEnabled(false);
        IncreaseVolume.setEnabled(true);
        DecreaseVolume.setEnabled(false);
        PlaySong.setEnabled(false);
    }//GEN-LAST:event_PlaySongActionPerformed

    private void DecreaseVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecreaseVolumeActionPerformed

       
        ConnectSpeaker.setEnabled(false);
        RadioOn.setEnabled(true);
        RadioOff.setEnabled(false);
        IncreaseVolume.setEnabled(true);
        DecreaseVolume.setEnabled(true);
    }//GEN-LAST:event_DecreaseVolumeActionPerformed

    private void RandomStationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomStationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RandomStationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhoneClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhoneClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhoneClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhoneClientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhoneClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConnectSpeaker;
    private javax.swing.JButton DecreaseVolume;
    private javax.swing.JButton IncreaseVolume;
    private javax.swing.JButton PhoneOff;
    private javax.swing.JButton PhoneOn;
    private javax.swing.JButton PlaySong;
    private javax.swing.JButton RadioOff;
    private javax.swing.JButton RadioOn;
    private javax.swing.JButton RandomStation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public void append(String string) {
        jTextArea1.append("\n" + string);
    }

    public void clear() {
        jTextArea1.setText("");
    }
}
