package clientui;

import client.PhoneClient;
import java.awt.Color;
import serviceui.Printer;

/**
 *
 * @author dominic
 */
public class PhoneClientGUI extends javax.swing.JFrame implements Printer {

    private PhoneClient client;

    public PhoneClientGUI() {
        initComponents();
    }

    public PhoneClientGUI(PhoneClient aThis) {
        this();
        this.client = aThis;
        PhoneOn.setEnabled(true);
        PhoneOff.setEnabled(false);
        PlaySong.setEnabled(false);
        Pause.setEnabled(false);
        VolumeUp.setEnabled(false);
        VolumeDown.setEnabled(false);
        Contacts.setEnabled(false);




    }
    
 
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PhoneOn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        PhoneOff = new javax.swing.JButton();
        PlaySong = new javax.swing.JButton();
        Pause = new javax.swing.JButton();
        VolumeUp = new javax.swing.JButton();
        VolumeDown = new javax.swing.JButton();
        Contacts = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        PhoneOn.setText("Phone On");
        PhoneOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneOnActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        PhoneOff.setText("Phone Off");
        PhoneOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneOffActionPerformed(evt);
            }
        });

        PlaySong.setText("Play MP3");
        PlaySong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlaySongActionPerformed(evt);
            }
        });

        Pause.setText("Pause");
        Pause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PauseActionPerformed(evt);
            }
        });

        VolumeUp.setText("volume up");
        VolumeUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeUpActionPerformed(evt);
            }
        });

        VolumeDown.setText("volume down");
        VolumeDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolumeDownActionPerformed(evt);
            }
        });

        Contacts.setText("Contacts");
        Contacts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Contacts)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneOn)
                            .addComponent(VolumeUp))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(VolumeDown)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Pause))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PhoneOff)
                                .addGap(18, 18, 18)
                                .addComponent(PlaySong)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PhoneOn)
                            .addComponent(PhoneOff)
                            .addComponent(PlaySong))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pause)
                            .addComponent(VolumeUp)
                            .addComponent(VolumeDown))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Contacts)
                        .addGap(13, 13, 13))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PhoneOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneOnActionPerformed
             
        
        client.turnphoneon();
        PhoneOn.setEnabled(false);
        PhoneOff.setEnabled(true);
        PlaySong.setEnabled(true);
        Pause.setEnabled(false);
        VolumeUp.setEnabled(true);
        VolumeDown.setEnabled(true);
        Contacts.setEnabled(true);

   


    }//GEN-LAST:event_PhoneOnActionPerformed

    private void PhoneOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneOffActionPerformed
        client.turnphoneoff();
        PhoneOff.setEnabled(false);
        PlaySong.setEnabled(false);
         PhoneOn.setEnabled(true);
        PhoneOff.setEnabled(false);
        PlaySong.setEnabled(false);
        Pause.setEnabled(false);
        VolumeUp.setEnabled(false);
        VolumeDown.setEnabled(false);
        Contacts.setEnabled(false);

      
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneOffActionPerformed

    private void PlaySongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlaySongActionPerformed
      client.playSong();
        PlaySong.setEnabled(true);
        Pause.setEnabled(true);
    
        
    }//GEN-LAST:event_PlaySongActionPerformed

    private void PauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PauseActionPerformed
   client.pause();
   PlaySong.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_PauseActionPerformed

    private void VolumeUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeUpActionPerformed
  client.volumeUp();
        // TODO add your handling code here:
    }//GEN-LAST:event_VolumeUpActionPerformed

    private void VolumeDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolumeDownActionPerformed
client.volumeDown();
        
        // TODO add your handling code here:
    }//GEN-LAST:event_VolumeDownActionPerformed

    private void ContactsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactsActionPerformed
client.showcontacts();
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PhoneClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PhoneClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PhoneClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PhoneClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PhoneClientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Contacts;
    private javax.swing.JButton Pause;
    private javax.swing.JButton PhoneOff;
    private javax.swing.JButton PhoneOn;
    private javax.swing.JButton PlaySong;
    private javax.swing.JButton VolumeDown;
    private javax.swing.JButton VolumeUp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public void append(String string) {
        jTextArea1.append("\n" + string);
    }

    public void clear() {
        jTextArea1.setText("");
    }
}
