# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommender.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "recommender.Recommendations" do
    repeated :movies, :message, 1, "recommender.Movie"
  end
  add_message "recommender.Movie" do
    optional :title, :string, 1
    optional :genre, :string, 2
    optional :director, :string, 3
  end
  add_message "recommender.Profile" do
    optional :age, :int32, 1
    optional :name, :string, 2
    repeated :seen, :message, 3, "recommender.Movie"
  end
end

module Recommender
  Recommendations = Google::Protobuf::DescriptorPool.generated_pool.lookup("recommender.Recommendations").msgclass
  Movie = Google::Protobuf::DescriptorPool.generated_pool.lookup("recommender.Movie").msgclass
  Profile = Google::Protobuf::DescriptorPool.generated_pool.lookup("recommender.Profile").msgclass
end
